name: Build Evolution X ROM for Poco M3
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git repo bc ccache
    - name: Initialize Repo
      run: |
        mkdir -p ~/rom
        cd ~/rom
        repo init -u git://github.com/Evolution-X/manifest -b tiramisu
    - name: Sync Source
      run: |
        cd ~/rom
        repo sync -c -j$(nproc --all) --force-sync
    - name: Clone Device, Kernel, and Vendor Trees
      run: |
        cd ~/rom
        git clone https://github.com/Joe7500/android_device_xiaomi_chime -b main device/xiaomi/chime
        git clone https://github.com/Joe7500/android_kernel_xiaomi_chime -b main kernel/xiaomi/chime
        git clone https://github.com/Joe7500/android_vendor_xiaomi_chime -b main vendor/xiaomi/chime
    - name: Build ROM
      run: |
        cd ~/rom
        source build/envsetup.sh
        lunch evo_chime-userdebug
        mka bacon -j$(nproc --all)
    - name: Upload ROM
      uses: actions/upload-artifact@v3
      with:
        name: evox-rom-output
        path: ~/rom/out/target/product/chime/*.zip
